import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Card from '../components/Card'
import Contact from '../components/Contact'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Projects from '../components/Projects'
import Services from '../components/Services'
import Skills from '../components/Skills'
import Work from '../components/Work'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Istiak | Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://unpkg.com/pattern.css" rel="stylesheet"></link>
      </Head>
      <Navbar/>
      <Header/>
      <About/>
      <Work/>
      {/* <Services/> */}
      <Skills/>
      <Projects/>
      <Contact/>
    </div>
  )
}
